[package]
name = "avr-pin"
version = "0.1.0"
edition = "2021"

[features]
atmega328p = []

[dependencies]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
lto = true
codegen-units = 1
panic = "abort"

